### ISSUE TITLE
repo structure

### ISSUE THREAD

**Issue by tobibeer** [ihm4u/tw5plugs#3]
Hi @ihm4u, can you perhaps rename the **plugins** folder in your **src** folder to **ihm4u**?

This allows me to include my local fork of your plugin in any of my **tiddlywiki.info** files as:

```
    "plugins": [
        "ihm4u/tidgraph"
    ],
```

rather than...

```
    "plugins": [
        "plugins/tidgraph"
    ],
```

Of course, you'd need to adjust your **tiddlywiki.info** files to match the default `<authorname>/<pluginname>` pattern.

**Comment by ihm4u** [comment]
sure, can you send me a PR, I'll merge right away

**Comment by tobibeer** [comment]
Before I do, for the [dict](https://github.com/tobibeer/tw5-dict) plugin, I have eventually settled to set up the folder structure as it is for [tiddlywiki](https://github.com/Jermolene/TiddlyWiki5/) itself, e.g.:
- **plugins**
  - tobibeer
    - dict
      - _plugin.info_
- **editions**
  - dict
    - _tiddlywiki.info_
    - tiddlers

Not only should this possibly cater for the default expectations of tiddlywiki CLI commands, I imagine this also makes the repo structure more relatable, as it looks the same as in [the tiddlywiki repo](https://github.com/Jermolene/TiddlyWiki5/).

So, at second thought, I'd suggest to also rename **src** to **plugins**. Let me know what you think / if this would break something for you.

**Comment by ihm4u** [comment]
Sure, that's great... the Makefile would need to be changed also with the new paths
I already have the editions like that, but not the plugins

**Comment by tobibeer** [comment]
Ok, another thing: While moving about folders I notice your plugin tiddlers are all named:

```
$:/plugins/ihm/tidgraph/...
```

rather than:

```
$:/plugins/ihm4u/tidgraph/...
```

Mhhh. What to do?

...or to put it like Shakespeare: "To change or not to change, that is the question." :D

Eventually it would be odd to have the plugin called:

```
$:/plugins/ihm4u/tidgraph
```

but the constituents all be...

```
$:/plugins/ihm/tidgraph/...
```

**Comment by tobibeer** [comment]
Ok, I think it's perhaps best to have you work this out yourself.

Here's how I have now come to work with repos, which will soon multiply rather quickly:
1. one repo per plugin — for greater manageability
2. each repo following the tiddlywiki folder structure — for maximum interoperability
3. (at least) one edition per plugin — called like the plugin — containing the docs / demos
   1. outputting an **index.html** to the repo root folder to be pushed to the **gh-pages** branch

Alternatively, you can sure have all plugins and editions in one big repo, like TiddlyWiki itself. However, for others interested in a particular plugin (using node), it would be easier to just pull its repo, rather than all your plugins / editions.

Why all this? To have the tiddlywiki CLI be fully functional both
- in your repo
- in other wiki folders wanting to include the plugin **ihm4u/tidgraph**
  - sure, we can always copy a given folder from your repo to a correct folder on our end
    - I'd prefer to not do that, to simply work with a repo as it is pulled form GitHub
      - could be a fork

Besides, you will run into problems when you try to include your plugin from another wiki folder outside your repo folder... unless you do the above copy & pasta.

Let me know if I can help.

**Comment by ihm4u** [comment]
hmm I see... I'll have to work on that later and split the plugins into separate repos...
can you just do a PR for the directory renaming ( with ihm not ihm4u) and I'll split plugins later.
thanks!

**Comment by tobibeer** [comment]
sorry wrong button

**Comment by tobibeer** [comment]
@ihm4u, may I ask: What does your makefile do / provide that would not be covered by the tiddlywiki CLI? (Sorry, not familiar with make.)

**Comment by ihm4u** [comment]
It does a whole bunch of stuff:
1. make dev  : 
    1.1 sets up a development environment by making symbolic links from the editions dir to the src dir
    1.2 waits for utils.js to be changed and it automatically kills the old node server and restarts it (this uses inotify)
    1.3 stays in this loop (waiting for a change to util.js and restarting the server) until I Ctrl+C out of it
2. make prod:
  2.1. deletes the development symbolic links
  2.2. minifies and optimizes the js code using the closure compiler
  2.3. builds the index.html file by calling the TW5 node build index command

there are other things, but those are the main ones

**Comment by tobibeer** [comment]
I see. I guess on my windows machine I'd be more trying to achieve these kinds of things with some node task runner like gulp... as @felixhayashi does, or grunt... who knows.

Not at that level of automation yet. And it's not been too much of a paint point for now... although, with the structure I have right now, I would not quite know where to output any minified plugins.

Perhaps that's really what a **dist** folder would be good for, one that is structured like the plugins folder but contains compacted code for distribution.

**Comment by ihm4u** [comment]
In windows things are a little bit more difficult...I'll close this issue since we already fixed the repo
